### PR TITLE
Update to newest Jest Snapshot

### PR DESCRIPTION
**Pull request by fatso83**
Has breaking API changes

### CODE REVIEW

**Comment by ethanresnick** [comment]
Thanks for this! I've merged. I wish this hadn't changed the import quote style (that just messes up git blame, distracts from the real changes in the diff), but not a blocker.

**Comment by ethanresnick** [comment]
FYI, I've fixed the tests here and republished this to npm as 3.0.0

**Comment by fatso83** [comment]
Sorry for not running tests in #2. I created the PR in a rush to submit it before picking up from day-care after discovering `UNDEFINED` in my snapshots (basically facebook/jest#5786), a by-product of upgrading `react-redux`.

I wouldn't normally submit a diff with unrelated changes either (which is why I made #1). Better luck next time, eh? :-)

**Comment by ethanresnick** [comment]
All good man. Thanks for figuring out the 23->24 API changes.

**Pull request merged**
